### ISSUE TITLE
Comparison with Restic 

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/docs#10]
I just discovered this now. I'm wondering if you could create some sort of feature comparison table to show how this compares to restic (and maybe even other popular tools) so that we can easily evaluate if this will suit our needs.

Moreover, perhaps it would be worth adding some detail to the readme explaining why this exists as opposed to just continuing to contribute to restic or others tools?

**Comment by ovizii** [comment]
Wanted to add a direct link: https://rustic.cli.rs/docs/comparison-restic.html
