### ISSUE TITLE
Fix repo init/copy documentation

### ISSUE THREAD

**Issue by Mr-Pi** [rustic-rs/docs#25]
Please fix or remove https://rustic.cli.rs/docs/commands/misc/deduplication.html

The correct approach for `rustic` seems to be `rustic copy --init` and to use a config file like https://github.com/rustic-rs/rustic/blob/main/config/copy_example.toml .

**Comment by aawsome** [comment]
Thanks a lot for opening the issue @Mr-Pi ! The documention in fact needs some rework.
I fixed this deduplication issues in #26 

Note: You can also easily propse PRs to the docu yourself by simply using the "edit" symbol on the top left!
