### ISSUE TITLE
Add examples for some storage providers

### ISSUE THREAD

**Issue by aawsome** [rustic-rs/docs#4]
In the example dir, there is currently only a real-life example of using local storage and of using OVH cloud archive/cloud storage as hot/cold storage (which is what I am using). Some more real-life examples might be good, e.g. using AWS glacier/standard S3 as hot/cold storage or storages of the other big public clouds.

**Comment by simonsan** [comment]
The documentation for storage providers is being done in `/config/services` in the main repository: https://github.com/rustic-rs/rustic/tree/main/config/services

I think it's easier to keep up-to-date there, as we also run CI tests against it. So closing this here now.
