### ISSUE TITLE
`rustic snapshots latest` not documented

### ISSUE THREAD

**Issue by Schweber** [rustic-rs/docs#76]
I'm using `rustic snapshots latest` in a script and just noticed that i can't find it anymore in `rustic snapshots --help` and on the [website](https://rustic.cli.rs/docs/commands/misc/listing.html).

Is this on purpose?

**Comment by aawsome** [comment]
@Schweber what do you mean by "can't find it anymore"?

There is no purpose and it will be always available as `rustic snapshots` uses the identical snapshots selection as other commands - which all do support `latest`.
