### ISSUE TITLE
Creating snapshots: error: unexpected argument '--verbose' found

### ISSUE THREAD

**Issue by yonas** [rustic-rs/docs#80]
https://rustic.cli.rs/docs/commands/backup/creating_snapshots.html

```sh
$ rustic -r /srv/rustic-repo --verbose backup ~/work

error: unexpected argument '--verbose' found

  tip: a similar argument exists: '--version'

Usage: rustic --version <--repository <REPOSITORY>|--repo-hot <REPO_HOT>> <COMMAND>

For more information, try '--help'.
```

**Comment by aawsome** [comment]
Thanks for reporting! Can you please open an issue to repair this (you can click the left top icon). rustic uses `--log-level=...` instead of `--verbose`.

**Comment by yonas** [comment]
@aawsome Done https://github.com/rustic-rs/docs/pull/81
